# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a316df8b286f8b30e6ecc7b3458a75ba810e6cf7d2b4d65e684853b8ee473cef4484cb64101d3d1a695b97ac9e3443c240e7fcaa64b527d12a746ef8da822dd

test:
  secret_key_base: 0865d5f585d1f1121993f035bfa91dcb5fa2a80266b16be17752ea50d8e890373975d31048dfefc97cc6852f09e689956261d672e5d4fac4a13cf6c7afcbd126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
